version: '3'
services: 
  ecs-pilot-builder:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ${GOPATH}/src:/go/src

    image:  ecs-pilot-builder
    container_name: ecs_pilot_builder
    environment:
      - GOOS=linux
      - GOARCH=amd64

  ecs-pilot-build-client:
      build: 
        context: .
        dockerfile: dockerfile
      volumes:
        - ${GOPATH}/src:/go/src
      image: ecs-pilot-builder
      container_name: ecs_pilot_client_builder
      entrypoint: "make server_client_integrate"
