version: '2'
services: 
  ecs-pilot-builder:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ${GOPATH}/src:/go/src

    image:  ecs-pilot
    container_name: ecs-pilot-builder
    environment:
      - GOOS=linux
      - GOARCH=amd64

