export const REQUEST_CLUSTERS = "REQUEST_CLUSTERS";
export const REQUEST_CLUSTERS_SUCCESS = "REQUEST_CLUSTERS_SUCCESS";
export const REQUEST_CLUSTERS_FAILURE = "REQUEST_CLUSTERS_FAILURE";

export const REQUEST_INSTANCES = "REQUEST_INSTANCES";
export const REQUEST_INSTANCES_SUCCESS = "REQUEST_INSTANCES_SUCCESS";
export const REQUEST_INSTANCES_FAILURE = "REQUEST_INSTANCES_FAILURE";

export const REQUEST_SECURITY_GROUPS = "REQUEST_SECURITY_GROUPS";
export const REQUEST_SECURITY_GROUPS_SUCCESS = "REQUEST_SECURITY_GROUPS_SUCCESS";
export const REQUEST_SECURITY_GROUPS_FAILURE = "REQUEST_SECURITY_GROUPS_FAILURE";

export const REQUEST_TASKS = "REQUEST_TASKS";
export const REQUEST_TASKS_SUCCESS = "REQUEST_TASKS_SUCCESS";
export const REQUEST_TASKS_FAILURE = "REQUEST_TASKS_FAILURE";

export const REQUEST_DEEP_TASKS = "REQUEST_DEEP_TASKS";
export const REQUEST_DEEP_TASKS_SUCCESS = "REQUEST_DEEP_TASKS_SUCCESS";
export const REQUEST_DEEP_TASKS_FAILURE = "REQUEST_DEEP_TASKS_FAILURE";

